// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20251111145036_V5")]
    partial class V5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("CenaKomunalija")
                        .HasColumnType("float");

                    b.Property<double>("CenaStruje")
                        .HasColumnType("float");

                    b.Property<double>("CenaVode")
                        .HasColumnType("float");

                    b.Property<int>("Mesec")
                        .HasColumnType("int");

                    b.Property<bool>("Placen")
                        .HasColumnType("bit");

                    b.Property<int?>("StanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StanID");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("WebTemplate.Models.Stan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojClanova")
                        .HasColumnType("int");

                    b.Property<int>("BrojStana")
                        .HasColumnType("int");

                    b.Property<string>("ImeVlasnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Povrsina")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Stanovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.HasOne("WebTemplate.Models.Stan", "Stan")
                        .WithMany("Racuni")
                        .HasForeignKey("StanID");

                    b.Navigation("Stan");
                });

            modelBuilder.Entity("WebTemplate.Models.Stan", b =>
                {
                    b.Navigation("Racuni");
                });
#pragma warning restore 612, 618
        }
    }
}
